// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5v0fPjnO8WcExOiRbh7w9DAyW32DU9xg',
    appId: '1:781197283147:web:924c05ac44872a413462ce',
    messagingSenderId: '781197283147',
    projectId: 'smart-fbd13',
    authDomain: 'smart-fbd13.firebaseapp.com',
    storageBucket: 'smart-fbd13.firebasestorage.app',
    measurementId: 'G-2BMKGQSNTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8pYiRE_gGJhd1tGuPjgvo6A0YcTxrG14',
    appId: '1:781197283147:android:e7339af3aaa58af73462ce',
    messagingSenderId: '781197283147',
    projectId: 'smart-fbd13',
    storageBucket: 'smart-fbd13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLxqLvm1oX3yh8CS8-uUtQ6M-n6LQURw',
    appId: '1:781197283147:ios:1bd87c760a3b76dd3462ce',
    messagingSenderId: '781197283147',
    projectId: 'smart-fbd13',
    storageBucket: 'smart-fbd13.firebasestorage.app',
    iosClientId: '781197283147-7q23ukkodsvddl6cgrisicko82rkmdkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFLxqLvm1oX3yh8CS8-uUtQ6M-n6LQURw',
    appId: '1:781197283147:ios:1bd87c760a3b76dd3462ce',
    messagingSenderId: '781197283147',
    projectId: 'smart-fbd13',
    storageBucket: 'smart-fbd13.firebasestorage.app',
    iosClientId: '781197283147-7q23ukkodsvddl6cgrisicko82rkmdkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5v0fPjnO8WcExOiRbh7w9DAyW32DU9xg',
    appId: '1:781197283147:web:d796b2f0df6d34523462ce',
    messagingSenderId: '781197283147',
    projectId: 'smart-fbd13',
    authDomain: 'smart-fbd13.firebaseapp.com',
    storageBucket: 'smart-fbd13.firebasestorage.app',
    measurementId: 'G-RR1WCT5TEM',
  );
}